apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass-docker
  annotations:
          tekton.dev/docker-0: https://index.docker.io # Described below
type: kubernetes.io/basic-auth
stringData:
  username: nawafabdullah0
  password: e8f76d17-0186-47d8-8849-8bd0729d6f09
