apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://gitlab.com/dewan_ahmed/go-tekton-openshift # If using GitLab, replace this with your GitLab repo url
